### PR TITLE
Propagate async errors to webpack

### LINKED ISSUE #77: webpack-dev-server fails on pug syntax error
I have webpack with my config. Everything is working as I expected. But when I trying to write my code with dev-server and pug-loader, something bad is going on. When pug has syntax error and throw exception, my dev-server is fails, and I must re-run it each time. 

**Issue**
In pug-loader (\node_modules\pug-loader\index.js) on string 155 we have `throw e`, and this is our problem, because pug loader do not return anything, just throw error. 

**Solution**
Just replace string 155 with `loaderContext.callback(e)`, and problem is gone. 

Here is shortlist of dependencies

```javascript
{
"pug": "^2.0.0-beta11",
"pug-loader": "^2.3.0",
"webpack": "^2.2.1",
"webpack-dev-server": "^2.3.0"
}
```

### PR DESCRIPTION
**Pull request by Pinpickle**
When compiling a module that has asynchronous errors (e.g. when an error results from using `extend` or `include`), the error will not go through Webpack, but will be thrown in some async handler somewhere.

This has two pretty big drawbacks:
- When watching files for changes, the entire process will exit when an error is thrown, as opposed to continuing and waiting for the error to be fixed (this is a deal breaker)
- The error does not go through Webpack's error reporting, which some tools may leverage.

I've fixed this by making all thrown errors in the `run` function go through the Webpack callback. I've added tests to check that this behaviour works, and I have verified that it fixed the problem in a project I am using `pug-loader` in.

I had to modify the mock Webpack loader system to actually be asynchronous, all tests should still be passing.

**Edit:** Turns out this fixes https://github.com/pugjs/pug-loader/issues/77 as well

### CODE REVIEW

**Comment by Pinpickle** [comment]
Looks like the Travis errors are because there is no `.travis.yml`?

File: test/fakeModuleSystem.js [hunk 1]
```diff
@@ -17,16 +17,16 @@ module.exports = function runLoader(loader, directory, filename, arg, callback)
...
 		},
-		loadModule: function(request, callback) {
+		loadModule: function(request, loadCallback) {
 			request = request.replace(/^-?!+/, "");
 			request = request.split("!");
 			var content = fs.readFileSync(request.pop(), "utf-8");
 			if(request[0] && /stringify/.test(request[0]))
 				content = JSON.stringify(content);
-			return callback(null, content);
+			process.nextTick(() => loadCallback(null, content));
```
Comment (TimothyGu) [inline test/fakeModuleSystem.js]: While at it, you can use `fs.readFile()` instead of `fs.readFileSync()` too.

**Review by TimothyGu — APPROVED** [review]
Looks good to me, other than a nit.

**Comment by TimothyGu** [comment]
Yeah, don't worry about Travis for now. I'll fix it when I find the time too. Thanks a lot!

**Comment by Pinpickle** [comment]
@TimothyGu I've made the file reading async now, as well as making `resolve` async in the mock runtime. How does this look now?
